services:
    # Listener doctrine for node modifications
    umanit.tree.doctrine.node_listener:
        class: Umanit\Bundle\TreeBundle\Doctrine\Listener\DoctrineTreeNodeListener
        arguments:
            - '@umanit.tree.node_helper'
        tags:
            - { name: 'doctrine.event_listener', event: postUpdate, priority: -10}
            - { name: 'doctrine.event_listener', event: postPersist, priority: -10 }
            - { name: 'doctrine.event_listener', event: preRemove, priority: -10 }
            - { name: 'doctrine.event_listener', event: postFlush, priority: -10 }

    # Listener doctrine for node modifications
    umanit.tree.doctrine.node_history_listener:
        class: Umanit\Bundle\TreeBundle\Doctrine\Listener\DoctrineNodeHistoryListener
        arguments:
            - '%umanit_tree.locale%'
        tags:
            - { name: 'doctrine.event_listener', event: postUpdate, priority: -20 }
            - { name: 'doctrine.event_listener', event: postPersist, priority: -20 }
            - { name: 'doctrine.event_listener', event: postRemove, priority: -20 }

    # Listener to redirect to the right controller
    umanit.tree.listener.route_listener:
        class: Umanit\Bundle\TreeBundle\Listener\RouteListener
        arguments:
            - '@doctrine'
            - '%umanit_tree.node_types%'
            - '%umanit_tree.locale%'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: -10 }

    # Router for nodes
    umanit.tree.router:
        class: Umanit\Bundle\TreeBundle\Router\NodeRouter
        arguments:
            - '@doctrine'
            - '@router'
            - '@request_stack'

    # Helpers twig for links
    umanit.tree.twig.extension.link:
        class: Umanit\Bundle\TreeBundle\Twig\Extension\LinkExtension
        arguments:
            - '@doctrine'
            - '@umanit.tree.router'
        tags:
            - { name: 'twig.extension' }

    # Helpers twig for SEO
    umanit.tree.twig.extension.seo:
        class: Umanit\Bundle\TreeBundle\Twig\Extension\SeoExtension
        arguments:
            - '@request_stack'
            - '@translator.default'
            - '%umanit_tree.seo%'
        tags:
            - { name: 'twig.extension' }

    # Helpers twig for SEO
    umanit.tree.twig.extension.breadcrumb:
        class: Umanit\Bundle\TreeBundle\Twig\Extension\BreadcrumbExtension
        arguments:
            - '@request_stack'
            - '@translator.default'
            - '%umanit_tree.breadcrumb%'
            - '@umanit.tree.router'
            - '@doctrine'
        tags:
            - { name: 'twig.extension' }

    # Helper for nodes
    umanit.tree.node_helper:
        class: Umanit\Bundle\TreeBundle\Helper\NodeHelper
        arguments:
            - '%umanit_tree.locale%'
            - '@doctrine'
            - '@event_dispatcher'

    # Link form type
    umanit.tree.form.type.link:
        class: Umanit\Bundle\TreeBundle\Form\Type\LinkType
        arguments:
            - '@doctrine'
            - '@translator.default'
        tags:
            - { name: 'form.type', alias: umanit_link_type }

    # node form type
    umanit.tree.form.type.node:
        class: Umanit\Bundle\TreeBundle\Form\Type\TreeNodeType
        calls:
            - ['setDoctrine', ['@doctrine']]
            - ['setTranslator', ['@translator.default']]
        tags:
            - { name: 'form.type', alias: umanit_node_type }

    # Menu form type
    umanit.tree.form.menu_type:
        class: '%umanit_tree.menu_form_class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%umanit_tree.node_types%'
            - '%umanit_tree.menu_entity_class%'
        tags:
            - { name: form.type, alias: umanit_tree_menu_type }

    # Menu injector
    umanit.tree.event_subscriber.menu_injector_subscriber:
        class: Umanit\Bundle\TreeBundle\EventSubscriber\MenuInjectorSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@twig'
            - '%umanit_tree.menu_entity_class%'

    # Twig configuration extension
    umanit.tree.twig.extension.configuration_extension:
        class: Umanit\Bundle\TreeBundle\Twig\Extension\ConfigurationExtension
        arguments: ['%umanit_tree.admin_layout%']
        tags:
            - { name: 'twig.extension' }